name: Shared Library CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
